In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.1047e+24, 4.5895e-41, 4.1047e+24],
        [4.5895e-41, 1.7034e+25, 7.3867e+20],
        [2.0027e-19, 1.7258e+25, 7.2065e+31],
        [2.7490e+20, 2.0319e-43, 0.0000e+00],
        [4.1047e+24, 4.5895e-41, 4.1047e+24]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3749, 0.1852, 0.8446],
        [0.7518, 0.0155, 0.3384],
        [0.9658, 0.3413, 0.2257],
        [0.7076, 0.3373, 0.9105],
        [0.8761, 0.8740, 0.5206]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-7.4871e-01,  6.2178e-04, -1.2007e-02],
        [-6.4537e-01, -1.3919e+00, -1.0562e+00],
        [-3.1809e-01,  1.3875e+00,  1.4351e+00],
        [ 3.9358e-01, -1.5171e-02,  4.6335e-01],
        [-1.7556e+00,  8.8941e-01,  1.2566e+00]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x * y)

tensor([[-2.9126e-01,  2.9026e-04, -3.9157e-04],
        [-3.5958e-01, -1.2090e+00, -5.5436e-01],
        [-7.5412e-02,  1.3632e+00,  9.7363e-01],
        [ 3.8311e-01, -5.0696e-03,  3.2624e-01],
        [-4.1841e-01,  8.0798e-01,  3.2058e-01]])


In [11]:
print(torch.add(x, y))

tensor([[-0.3597,  0.4674,  0.0206],
        [-0.0882, -0.5233, -0.5313],
        [-0.0810,  2.3700,  2.1135],
        [ 1.3670,  0.3190,  1.1674],
        [-1.5172,  1.7979,  1.5117]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3597,  0.4674,  0.0206],
        [-0.0882, -0.5233, -0.5313],
        [-0.0810,  2.3700,  2.1135],
        [ 1.3670,  0.3190,  1.1674],
        [-1.5172,  1.7979,  1.5117]])


In [14]:
#in-placeで置き換える関数は、すべて_がついている。add_, copy_など。
y.add_(x)
print(y)

tensor([[-1.1084,  0.4681,  0.0086],
        [-0.7336, -1.9153, -1.5875],
        [-0.3991,  3.7575,  3.5486],
        [ 1.7605,  0.3038,  1.6308],
        [-3.2728,  2.6873,  2.7684]])


In [15]:
print(x[:, 1])

tensor([ 6.2178e-04, -1.3919e+00,  1.3875e+00, -1.5171e-02,  8.8941e-01])


In [16]:
#Numpyのreshapeはview
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
#tensorから1つの要素を取り出すのに、item()
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0825])
-0.08251699060201645


In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
#ndarray, tensorはCPUで展開されるとき、変更を共有する。
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
